server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  application:
    name: profile-api
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.timezone.default_storage: NORMALIZE
---
spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 123456
---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:mariadb://${DEV_DB_URL}:${DEV_DB_PORT}/${DEV_DB_NAME}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}